---

name: CI

on:
  - pull_request
  - push

jobs:
  Format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Compile
      run: docker-compose build

    - name: Format
      run: docker-compose run houston format

  Test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Compile
      run: docker-compose build

    - name: Test
      run: docker-compose run houston test
